### PR TITLE
feat: Success/error callbacks

### PR DESCRIPTION
**Pull request by moonmeister**
Adding a callback to trigger after form submission

Currently has merges from #16  as well, Once the other is merged this will cleanup.

### CODE REVIEW

**Comment by moonmeister** [comment]
Should be ready to go.

**Comment by robmarshall** [comment]
Some really great stuff here. I have merged the other PR. Let me know when the cleanups have been completed and I will get it merged.

**Comment by robmarshall** [comment]
Do you use this alongside the gatsby-source-gravityforms plugin? If so, have you been updating the source plugins queries to ensure this component can grab the right data?

If not, I would love to know your way of getting the form data from Gatsby. These updated queries would not be working otherwise.

**Comment by moonmeister** [comment]
@robmarshall Okay, re-based onto master, should be only the relevant commits. Yes, I use your source plugin. I was just checking out https://github.com/harness-software/wp-graphql-gravity-forms because I'm also using wpgraphql, but it's not mature enough to be using yet.

**Pull request merged**
