### PR TITLE
Fix request structure

### PR DESCRIPTION
**Pull request by moonmeister**
The axios post  function for form data wasn't called correctly, cleaned it up and fixed the example api to match. This is a breaking change.

### CODE REVIEW

**Comment by robmarshall** [comment]
Would you be able to bump the version number in the package.json. I am pretty busy atm so would be a massive help.

**Comment by moonmeister** [comment]
@robmarshall Bumped the version and added a change-log to assist  those looking to upgrade.

**Comment by moonmeister** [comment]
Let me know if there's anything else I can do to help move this along. Thanks Rob!

**Comment by robmarshall** [comment]
Merged into master and published to NPM. Thanks for the great work!

**Pull request merged**
